# Generated by Django 3.0.7 on 2020-06-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
    ]
